### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by rock16** [aad-team-45/aad-team-45-animation-challenge#3]
- [ ] work on repository

**Comment by staa99** [comment]
@rock16 You've not explained the details of the project to us team members yet. I know you intend to integrate with Google book API but I don't know any other thing. So I suggest you give a proper briefing on the channel to get everyone up to date.

**Comment by rock16** [comment]
I'm putting that in place now. Later in the day. You guys are going to have
it.

**Comment by rock16** [comment]
I'm putting that in place. Later in the day,  you guys are going to have
it.

**Comment by staa99** [comment]
Ok good
